name = "FancyMakie"
uuid = "aa8846d6-bb89-4e5c-8db1-9add4ad434f9"
version = "0.1.1"
authors = ["28tob "]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"

[compat]
CairoMakie = "0.15.8"
LaTeXStrings = "1.4.0"
